In [1]:
import numpy as np

In [2]:
print ('q1-1')
A = np.random.randn(4, 3)
print(A)

q1-1
[[-1.4393227   0.10893212 -0.02877966]
 [ 0.34425901 -0.01989261  0.6541101 ]
 [ 0.9737709  -1.87746134 -0.29620171]
 [-0.08147097 -0.16050659  0.04604445]]


In [3]:
print ('q1-2')
x = np.random.randn(4,1)
print(x)

q1-2
[[ 1.36343552]
 [ 0.92179925]
 [-0.38837113]
 [-1.37590676]]


In [4]:
print ('q1-3')
B = A.reshape(2,6)
print(B)

q1-3
[[-1.4393227   0.10893212 -0.02877966  0.34425901 -0.01989261  0.6541101 ]
 [ 0.9737709  -1.87746134 -0.29620171 -0.08147097 -0.16050659  0.04604445]]


In [6]:
print ('q1-4')
#Broadcasting
C =A+x
print(C)

q1-4
[[-0.07588719  1.47236763  1.33465585]
 [ 1.26605826  0.90190665  1.57590935]
 [ 0.58539977 -2.26583247 -0.68457285]
 [-1.45737773 -1.53641335 -1.32986231]]


In [8]:
print('q1-5')
y =x.flatten() #
print(y)

q1-5
[ 1.36343552  0.92179925 -0.38837113 -1.37590676]


In [9]:
print ('q1-6')
A[:,0] = np.transpose(y)
print(A)

q1-6
[[ 1.36343552  0.10893212 -0.02877966]
 [ 0.92179925 -0.01989261  0.6541101 ]
 [-0.38837113 -1.87746134 -0.29620171]
 [-1.37590676 -0.16050659  0.04604445]]


In [10]:
print ('q1-7')
A[:,0] = A[:,2]+np.transpose(y)
print(A)

q1-7
[[ 1.33465585  0.10893212 -0.02877966]
 [ 1.57590935 -0.01989261  0.6541101 ]
 [-0.68457285 -1.87746134 -0.29620171]
 [-1.32986231 -0.16050659  0.04604445]]


In [11]:
print ('q1-8')

print(A[:,0:2])

q1-8
[[ 1.33465585  0.10893212]
 [ 1.57590935 -0.01989261]
 [-0.68457285 -1.87746134]
 [-1.32986231 -0.16050659]]


In [15]:
print ('q1-9')

print(A[[0,2],:])

q1-9
[[ 1.33465585  0.10893212 -0.02877966]
 [-0.68457285 -1.87746134 -0.29620171]]


In [20]:
print ('q1-10')
s = A.sum(axis=0)
print(s)

q1-10
[ 0.89613005 -1.94892842  0.37517317]


In [21]:
print ('q1-11')
m = A.max(axis=1)
print(m)

q1-11
[ 1.33465585  1.57590935 -0.29620171  0.04604445]


In [22]:
print ('q1-12')
m = np.sum(A)/(A.shape[0]*A.shape[1])
print(m)

q1-12
-0.05646876712204662


In [25]:
print ('q1-13')
L = np.log(np.square(A))
print(L)

q1-13
[[ 0.57734694 -4.4340607  -7.09617272]
 [ 0.90966494 -7.83481433 -0.8489592 ]
 [-0.75792043  1.25984102 -2.43342919]
 [ 0.57015082 -3.6588405  -6.15629623]]


In [26]:
print ('q1-14')
t = np.matmul( A.transpose(),x)
print(t)

q1-14
[[5.36802412]
 [1.08017883]
 [0.61540232]]
